apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  dbUser: {{ .Values.db.user | b64enc }}
  dbPassword: {{ .Values.db.password | b64enc }}
  blobStoreAccessKey: {{ .Values.blobStore.accessKeyId | b64enc }}
  blobStoreAccessSecretKey: {{ .Values.blobStore.accessSecretKey | b64enc }}
