apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-manager-go
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-dev-dependencies
          image: busybox:1.28
          command: [ 'sh', '-c', 'sleep 15' ]
