# https://vektra.github.io/mockery/latest/configuration
# --------------------------------------------------
# V2 deprecations
issue-845-fix: True
resolve-type-alias: False
# --------------------------------------------------
with-expecter: True
filename: "{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/sdreger/lib-manager-go/cmd/api/handlers/v1:
    interfaces:
      BookService:
      CoverService:
  github.com/sdreger/lib-manager-go/internal/domain/book:
    interfaces:
      Store:
  github.com/sdreger/lib-manager-go/internal/domain/cover:
    interfaces:
      BlobStore:
