# https://vektra.github.io/mockery/latest/configuration
# --------------------------------------------------
all: false
dir: '{{.InterfaceDir}}'
structname: 'Mock{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
filename: "{{.InterfaceName | snakecase}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
recursive: false
template: testify
template-data:
  mock-build-tags: '!build'
packages:
  github.com/sdreger/lib-manager-go/cmd/api/handlers/v1:
    interfaces:
      BookService: {}
      CoverService: {}
      FileTypeService: {}
  github.com/sdreger/lib-manager-go/internal/domain/book:
    interfaces:
      Store: {}
  github.com/sdreger/lib-manager-go/internal/domain/cover:
    interfaces:
      BlobStore: {}
  github.com/sdreger/lib-manager-go/internal/domain/filetype:
    interfaces:
      Store: {}
  github.com/sdreger/lib-manager-go/internal/domain/publisher:
    interfaces:
      Store: {}
