apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: lib-manager-go
    envs:
      - .configmap.env
secretGenerator:
  - name: lib-manager-go
    envs:
      - .secret.env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
