apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30001
      hostPort: 30001 # application API port
    - containerPort: 30002
      hostPort: 30002 # Postgres port
    - containerPort: 30003
      hostPort: 30003 # Minio API port
    - containerPort: 30004
      hostPort: 30004 # Minio Console port
  extraMounts:
    - hostPath: ./ca.pem
      containerPath: /etc/ssl/certs/traefik.pem
