apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-manager-go
  annotations:
    ignore-check.kube-linter.io/latest-tag: "the tag is set by the deployment system"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lib-manager-go
  strategy: {}
  template:
    metadata:
      labels:
        app: lib-manager-go
    spec:
      containers:
        - image: gitea.dreger.lan/sdreger/lib-manager-go:latest
          name: lib-manager-go
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          envFrom:
            - secretRef:
                name: lib-manager-go
            - configMapRef:
                name: lib-manager-go
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources: {}
