apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lib-manager
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
components:
  - ../components/app_config
  - ../components/app_ports
