apiVersion: v1
kind: Service
metadata:
  name: lib-manager-go
spec:
  ports:
    - name: http
      port: 8070
      targetPort: 8070
      protocol: TCP
  selector:
    app: lib-manager-go
  type: ClusterIP
