name: Build, test and perform static code analysis
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Show Go version
        run: go version
      - name: Download dependencies
        run: go mod download
      - name: Verify dependencies
        run: |
          go mod verify
          go mod tidy --diff
      - name: Verify code formatting
        run: test -z "$(gofmt -l .)"
      - name: Perform static analysis (go vet)
        run: go vet ./...
      - name: Perform static analysis (staticcheck)
        uses: dominikh/staticcheck-action@v1
        with:
          checks: all,-ST1000,-U1000
          version: "latest"
          install-go: false
      - name: Perform lint checks
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          args: -E testifylint -v ./...
      - name: Perform vulnerability analysis
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'
          go-package: ./...
      - name: Build the code
        run: go build -o /dev/null ./...
      - name: Run tests
        run: |
          go test -v -race -shuffle=on -buildvcs ./...
