name: Run Pact contract verification
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '0.0.5'

jobs:
  pact-integration-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ gitea.event.inputs.version }}
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Download dependencies
        run: go mod download
      - name: Run integration tests
        run: |
          PACT_DO_NOT_TRACK=true PACT_PUBLISH_RESULTS=true \
          PACT_BROKER_URL=${{ vars.PACT_BROKER_URL }} PACT_PROVIDER_NAME=lib-manager-go \
          PACT_VERSION_BRANCH=main PACT_VERSION_COMMIT=${{ gitea.event.inputs.version }} \
          go test -tags=integration -count=1 github.com/sdreger/lib-manager-go/cmd/api -run 'TestPactProvider' -v
