// Code generated by mockery v2.52.1. DO NOT EDIT.

package book

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, bookID
func (_m *MockStore) GetByID(ctx context.Context, bookID int64) (Book, error) {
	ret := _m.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (Book, error)); ok {
		return rf(ctx, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) Book); ok {
		r0 = rf(ctx, bookID)
	} else {
		r0 = ret.Get(0).(Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID int64
func (_e *MockStore_Expecter) GetByID(ctx interface{}, bookID interface{}) *MockStore_GetByID_Call {
	return &MockStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, bookID)}
}

func (_c *MockStore_GetByID_Call) Run(run func(ctx context.Context, bookID int64)) *MockStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_GetByID_Call) Return(_a0 Book, _a1 error) *MockStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetByID_Call) RunAndReturn(run func(context.Context, int64) (Book, error)) *MockStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
