apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: lib-manager-go
      fieldPath: data.LIB_MANAGER_HTTP_PORT
    targets:
      - select:
          kind: Deployment
          name: lib-manager-go
        fieldPaths:
          - spec.template.spec.containers.[name=lib-manager-go].ports.[name=http].containerPort
      - select:
          kind: Service
          name: lib-manager-go
        fieldPaths:
          - spec.ports.0.port
          - spec.ports.0.targetPort
