apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/app_ports
patches:
  - path: patch_resources.yaml
labels:
  - pairs:
      app: lib-manager-go
    includeSelectors: false
images:
  - name: gitea.dreger.lan/sdreger/lib-manager-go:latest
    newName: gitea.dreger.lan/sdreger/lib-manager-go
    newTag: 0.0.3
replicas:
  - count: 3
    name: lib-manager-go
configMapGenerator:
  - name: lib-manager-go
    behavior: merge
    literals:
      - LIB_MANAGER_HTTP_PORT=8050
      - LIB_MANAGER_DB_HOST=postgres.dreger.lan
      - LIB_MANAGER_DB_NAME=digital_assets
      - LIB_MANAGER_BLOB_STORE_MINIO_ENDPOINT=minio.dreger.lan:9000
secretGenerator:
  - name: lib-manager-go
    behavior: merge
    envs:
      - .secret.encrypted.env
