apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-manager-go
spec:
  template:
    spec:
      containers:
        - name: lib-manager-go
          resources:
            requests:
              cpu: '0.2'
              memory: '256Mi'
            limits:
              cpu: '0.8'
              memory: '512Mi'
