// Code generated by mockery v2.52.1. DO NOT EDIT.

package v1

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCoverService is an autogenerated mock type for the CoverService type
type MockCoverService struct {
	mock.Mock
}

type MockCoverService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoverService) EXPECT() *MockCoverService_Expecter {
	return &MockCoverService_Expecter{mock: &_m.Mock}
}

// GetBookCover provides a mock function with given fields: ctx, filePath
func (_m *MockCoverService) GetBookCover(ctx context.Context, filePath string) (io.Reader, error) {
	ret := _m.Called(ctx, filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetBookCover")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.Reader, error)); ok {
		return rf(ctx, filePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.Reader); ok {
		r0 = rf(ctx, filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoverService_GetBookCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookCover'
type MockCoverService_GetBookCover_Call struct {
	*mock.Call
}

// GetBookCover is a helper method to define mock.On call
//   - ctx context.Context
//   - filePath string
func (_e *MockCoverService_Expecter) GetBookCover(ctx interface{}, filePath interface{}) *MockCoverService_GetBookCover_Call {
	return &MockCoverService_GetBookCover_Call{Call: _e.mock.On("GetBookCover", ctx, filePath)}
}

func (_c *MockCoverService_GetBookCover_Call) Run(run func(ctx context.Context, filePath string)) *MockCoverService_GetBookCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoverService_GetBookCover_Call) Return(_a0 io.Reader, _a1 error) *MockCoverService_GetBookCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoverService_GetBookCover_Call) RunAndReturn(run func(context.Context, string) (io.Reader, error)) *MockCoverService_GetBookCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoverService creates a new instance of MockCoverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoverService {
	mock := &MockCoverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
