// Code generated by mockery v2.52.1. DO NOT EDIT.

package filetype

import (
	context "context"

	paging "github.com/sdreger/lib-manager-go/internal/paging"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function with given fields: ctx, page, sort
func (_m *MockStore) Lookup(ctx context.Context, page paging.PageRequest, sort paging.Sort) ([]LookupItem, int64, error) {
	ret := _m.Called(ctx, page, sort)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 []LookupItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, paging.PageRequest, paging.Sort) ([]LookupItem, int64, error)); ok {
		return rf(ctx, page, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paging.PageRequest, paging.Sort) []LookupItem); ok {
		r0 = rf(ctx, page, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]LookupItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paging.PageRequest, paging.Sort) int64); ok {
		r1 = rf(ctx, page, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, paging.PageRequest, paging.Sort) error); ok {
		r2 = rf(ctx, page, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockStore_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ctx context.Context
//   - page paging.PageRequest
//   - sort paging.Sort
func (_e *MockStore_Expecter) Lookup(ctx interface{}, page interface{}, sort interface{}) *MockStore_Lookup_Call {
	return &MockStore_Lookup_Call{Call: _e.mock.On("Lookup", ctx, page, sort)}
}

func (_c *MockStore_Lookup_Call) Run(run func(ctx context.Context, page paging.PageRequest, sort paging.Sort)) *MockStore_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(paging.PageRequest), args[2].(paging.Sort))
	})
	return _c
}

func (_c *MockStore_Lookup_Call) Return(_a0 []LookupItem, _a1 int64, _a2 error) *MockStore_Lookup_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_Lookup_Call) RunAndReturn(run func(context.Context, paging.PageRequest, paging.Sort) ([]LookupItem, int64, error)) *MockStore_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
